### PR TITLE
Update "master" branch references to "main"

### PR DESCRIPTION
**Pull request by denyeart**
Update "master" branch references to "main".

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

### CODE REVIEW

**Comment by denyeart** [comment]
@bestbeforetoday Could you review?

**Review by bestbeforetoday — APPROVED** [review]

**Comment by bestbeforetoday** [comment]
@denyeart Looks OK to me but I don't have permission to merge it without a passing PR build, and this one hasn't run

**Comment by denyeart** [comment]
Ok, I've merged and updated default branch to "main", that should fix CI going forward.

**Pull request merged**
